const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Package = require('./models/Package');
const User = require('./models/User');
const Booking = require('./models/Booking');

dotenv.config({ path: './.env' });

const DB = process.env.DATABASE_URL;

mongoose
  .connect(DB)
  .then(() => console.log('DB connection successful!'))
  .catch((err) => console.log('DB connection error:', err));

const seedDB = async () => {
  try {
    await Package.deleteMany();
    await User.deleteMany();
    await Booking.deleteMany();

    const adminUser = await User.create({
      name: 'Admin Priya',
      email: 'admin@travelease.com',
      password: 'password123',
      role: 'admin'
    });

    const regularUser = await User.create({
      name: 'John Doe',
      email: 'john@example.com',
      password: 'password123',
      role: 'user'
    });

    const packages = await Package.create([
      {
        title: 'Tropical Paradise in Bali',
        destination: 'Bali, Indonesia',
        description: 'Experience the magic of Bali with its stunning beaches, lush jungles, and vibrant culture.',
        price: 1200,
        duration: '7 Days',
        availableSeats: 15,
        startDate: new Date('2026-07-15'),
        image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Swiss Alps Adventure',
        destination: 'Zermatt, Switzerland',
        description: 'Ski down the majestic Swiss Alps and enjoy breathtaking mountain views.',
        price: 2500,
        duration: '5 Days',
        availableSeats: 10,
        startDate: new Date('2026-12-20'),
        image: 'https://images.unsplash.com/photo-1533240332313-0cb49f471b20?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Mystical Kyoto',
        destination: 'Kyoto, Japan',
        description: 'Discover the ancient temples and beautiful Zen gardens of Kyoto.',
        price: 1800,
        duration: '6 Days',
        availableSeats: 12,
        startDate: new Date('2026-10-05'),
        image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Safari Explorer',
        destination: 'Serengeti, Tanzania',
        description: 'Witness the great migration and experience the wild beauty of Africa.',
        price: 3200,
        duration: '8 Days',
        availableSeats: 8,
        startDate: new Date('2026-08-10'),
        image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Taj Mahal Tour',
        destination: 'Agra, India',
        description: 'Explore the architectural wonder of the world and dive deep into Mughal history.',
        price: 15000,
        duration: '3 Days',
        availableSeats: 20,
        startDate: new Date('2026-09-01'),
        image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Serene Kerala Backwaters',
        destination: 'Kerala, India',
        description: 'Relax on traditional houseboats floating through the lush green backwaters of God\'s Own Country.',
        price: 25000,
        duration: '5 Days',
        availableSeats: 12,
        startDate: new Date('2026-11-15'),
        image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Royal Rajasthan Heritage',
        destination: 'Jaipur, India',
        description: 'Experience the grandeur of ancient forts, vibrant markets, and royal palaces in the Pink City.',
        price: 30000,
        duration: '6 Days',
        availableSeats: 18,
        startDate: new Date('2026-10-20'),
        image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Goa Beach Getaway',
        destination: 'Goa, India',
        description: 'Enjoy sun-kissed beaches, thrilling water sports, and vibrant nightlife in India\'s party capital.',
        price: 18000,
        duration: '4 Days',
        availableSeats: 25,
        startDate: new Date('2026-12-05'),
        image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
      }
,
      {
        title: 'Incredible Kanyakumari Explorer',
        destination: 'Kanyakumari, Tamil Nadu',
        description: 'Experience the best of Kanyakumari, Tamil Nadu with our carefully curated 5 days itinerary full of scenic views and local culture.',
        price: 27000,
        duration: '5 Days',
        availableSeats: 12,
        startDate: new Date('2026-03-24'),
        image: 'https://images.unsplash.com/photo-1587474260580-5883ea07fe30?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Peaceful Kochi Escape',
        destination: 'Kochi, Kerala',
        description: 'Experience the best of Kochi, Kerala with our carefully curated 8 days itinerary full of scenic views and local culture.',
        price: 15000,
        duration: '8 Days',
        availableSeats: 6,
        startDate: new Date('2026-01-03'),
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Gokarna Sojourn',
        destination: 'Gokarna, Karnataka',
        description: 'Experience the best of Gokarna, Karnataka with our carefully curated 10 days itinerary full of scenic views and local culture.',
        price: 11000,
        duration: '10 Days',
        availableSeats: 11,
        startDate: new Date('2026-12-21'),
        image: 'https://images.unsplash.com/photo-1570168007204-dfb528c68ddf?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Historic Gokarna Sojourn',
        destination: 'Gokarna, Karnataka',
        description: 'Experience the best of Gokarna, Karnataka with our carefully curated 2 days itinerary full of scenic views and local culture.',
        price: 27000,
        duration: '2 Days',
        availableSeats: 29,
        startDate: new Date('2026-03-23'),
        image: 'https://images.unsplash.com/photo-1570168007204-dfb528c68ddf?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Breathtaking Auli Retreat',
        destination: 'Auli, Uttarakhand',
        description: 'Experience the best of Auli, Uttarakhand with our carefully curated 7 days itinerary full of scenic views and local culture.',
        price: 23000,
        duration: '7 Days',
        availableSeats: 8,
        startDate: new Date('2026-02-13'),
        image: 'https://images.unsplash.com/photo-1587474260580-5883ea07fe30?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Serene Spiti Valley Sojourn',
        destination: 'Spiti Valley, Himachal Pradesh',
        description: 'Experience the best of Spiti Valley, Himachal Pradesh with our carefully curated 2 days itinerary full of scenic views and local culture.',
        price: 26000,
        duration: '2 Days',
        availableSeats: 28,
        startDate: new Date('2026-08-18'),
        image: 'https://images.unsplash.com/photo-1587474260580-5883ea07fe30?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Incredible Coorg Escape',
        destination: 'Coorg, Karnataka',
        description: 'Experience the best of Coorg, Karnataka with our carefully curated 7 days itinerary full of scenic views and local culture.',
        price: 28000,
        duration: '7 Days',
        availableSeats: 23,
        startDate: new Date('2026-04-23'),
        image: 'https://images.unsplash.com/photo-1587474260580-5883ea07fe30?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Munnar Journey',
        destination: 'Munnar, Kerala',
        description: 'Experience the best of Munnar, Kerala with our carefully curated 3 days itinerary full of scenic views and local culture.',
        price: 28000,
        duration: '3 Days',
        availableSeats: 12,
        startDate: new Date('2026-02-13'),
        image: 'https://images.unsplash.com/photo-1623126040845-cb005e80db80?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Gantok Tour',
        destination: 'Gantok, Sikkim',
        description: 'Experience the best of Gantok, Sikkim with our carefully curated 7 days itinerary full of scenic views and local culture.',
        price: 20000,
        duration: '7 Days',
        availableSeats: 16,
        startDate: new Date('2026-04-22'),
        image: 'https://images.unsplash.com/photo-1623126040845-cb005e80db80?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Kumarakom Holiday',
        destination: 'Kumarakom, Kerala',
        description: 'Experience the best of Kumarakom, Kerala with our carefully curated 4 days itinerary full of scenic views and local culture.',
        price: 14000,
        duration: '4 Days',
        availableSeats: 22,
        startDate: new Date('2026-12-08'),
        image: 'https://images.unsplash.com/photo-1514222026857-79758525baf3?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Vibrant Gantok Expedition',
        destination: 'Gantok, Sikkim',
        description: 'Experience the best of Gantok, Sikkim with our carefully curated 10 days itinerary full of scenic views and local culture.',
        price: 50000,
        duration: '10 Days',
        availableSeats: 12,
        startDate: new Date('2026-11-11'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Magical Gokarna Tour',
        destination: 'Gokarna, Karnataka',
        description: 'Experience the best of Gokarna, Karnataka with our carefully curated 6 days itinerary full of scenic views and local culture.',
        price: 35000,
        duration: '6 Days',
        availableSeats: 7,
        startDate: new Date('2026-04-19'),
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Pondicherry Experience',
        destination: 'Pondicherry',
        description: 'Experience the best of Pondicherry with our carefully curated 9 days itinerary full of scenic views and local culture.',
        price: 35000,
        duration: '9 Days',
        availableSeats: 9,
        startDate: new Date('2026-05-05'),
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Ranthambore Escape',
        destination: 'Ranthambore, Rajasthan',
        description: 'Experience the best of Ranthambore, Rajasthan with our carefully curated 8 days itinerary full of scenic views and local culture.',
        price: 26000,
        duration: '8 Days',
        availableSeats: 23,
        startDate: new Date('2026-07-12'),
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Andaman Islands Experience',
        destination: 'Andaman Islands',
        description: 'Experience the best of Andaman Islands with our carefully curated 2 days itinerary full of scenic views and local culture.',
        price: 15000,
        duration: '2 Days',
        availableSeats: 8,
        startDate: new Date('2026-03-21'),
        image: 'https://images.unsplash.com/photo-1514222026857-79758525baf3?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Gir Adventure',
        destination: 'Gir, Gujarat',
        description: 'Experience the best of Gir, Gujarat with our carefully curated 3 days itinerary full of scenic views and local culture.',
        price: 48000,
        duration: '3 Days',
        availableSeats: 17,
        startDate: new Date('2026-07-20'),
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Breathtaking Pushkar Escape',
        destination: 'Pushkar, Rajasthan',
        description: 'Experience the best of Pushkar, Rajasthan with our carefully curated 3 days itinerary full of scenic views and local culture.',
        price: 10000,
        duration: '3 Days',
        availableSeats: 26,
        startDate: new Date('2026-09-25'),
        image: 'https://images.unsplash.com/photo-1623126040845-cb005e80db80?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Sundarbans Tour',
        destination: 'Sundarbans, West Bengal',
        description: 'Experience the best of Sundarbans, West Bengal with our carefully curated 6 days itinerary full of scenic views and local culture.',
        price: 17000,
        duration: '6 Days',
        availableSeats: 18,
        startDate: new Date('2026-03-15'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Peaceful Kanha Expedition',
        destination: 'Kanha, Madhya Pradesh',
        description: 'Experience the best of Kanha, Madhya Pradesh with our carefully curated 4 days itinerary full of scenic views and local culture.',
        price: 42000,
        duration: '4 Days',
        availableSeats: 21,
        startDate: new Date('2026-02-28'),
        image: 'https://images.unsplash.com/photo-1623126040845-cb005e80db80?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Kanyakumari Sojourn',
        destination: 'Kanyakumari, Tamil Nadu',
        description: 'Experience the best of Kanyakumari, Tamil Nadu with our carefully curated 4 days itinerary full of scenic views and local culture.',
        price: 22000,
        duration: '4 Days',
        availableSeats: 16,
        startDate: new Date('2026-03-18'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Serene Madurai Experience',
        destination: 'Madurai, Tamil Nadu',
        description: 'Experience the best of Madurai, Tamil Nadu with our carefully curated 3 days itinerary full of scenic views and local culture.',
        price: 11000,
        duration: '3 Days',
        availableSeats: 16,
        startDate: new Date('2026-05-08'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Beautiful Kodaikanal Getaway',
        destination: 'Kodaikanal, Tamil Nadu',
        description: 'Experience the best of Kodaikanal, Tamil Nadu with our carefully curated 9 days itinerary full of scenic views and local culture.',
        price: 15000,
        duration: '9 Days',
        availableSeats: 7,
        startDate: new Date('2026-09-25'),
        image: 'https://images.unsplash.com/photo-1514222026857-79758525baf3?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Andaman Islands Experience',
        destination: 'Andaman Islands',
        description: 'Experience the best of Andaman Islands with our carefully curated 4 days itinerary full of scenic views and local culture.',
        price: 45000,
        duration: '4 Days',
        availableSeats: 13,
        startDate: new Date('2026-09-28'),
        image: 'https://images.unsplash.com/photo-1570168007204-dfb528c68ddf?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Pondicherry Journey',
        destination: 'Pondicherry',
        description: 'Experience the best of Pondicherry with our carefully curated 8 days itinerary full of scenic views and local culture.',
        price: 29000,
        duration: '8 Days',
        availableSeats: 26,
        startDate: new Date('2026-11-12'),
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Historic Pushkar Getaway',
        destination: 'Pushkar, Rajasthan',
        description: 'Experience the best of Pushkar, Rajasthan with our carefully curated 5 days itinerary full of scenic views and local culture.',
        price: 25000,
        duration: '5 Days',
        availableSeats: 7,
        startDate: new Date('2026-06-01'),
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Enchanting Tirupati Explorer',
        destination: 'Tirupati, Andhra Pradesh',
        description: 'Experience the best of Tirupati, Andhra Pradesh with our carefully curated 2 days itinerary full of scenic views and local culture.',
        price: 14000,
        duration: '2 Days',
        availableSeats: 12,
        startDate: new Date('2026-02-02'),
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Darjeeling Journey',
        destination: 'Darjeeling, West Bengal',
        description: 'Experience the best of Darjeeling, West Bengal with our carefully curated 9 days itinerary full of scenic views and local culture.',
        price: 27000,
        duration: '9 Days',
        availableSeats: 11,
        startDate: new Date('2026-09-05'),
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Historic Kodaikanal Adventure',
        destination: 'Kodaikanal, Tamil Nadu',
        description: 'Experience the best of Kodaikanal, Tamil Nadu with our carefully curated 3 days itinerary full of scenic views and local culture.',
        price: 22000,
        duration: '3 Days',
        availableSeats: 8,
        startDate: new Date('2026-11-14'),
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Vibrant Tawang Experience',
        destination: 'Tawang, Arunachal Pradesh',
        description: 'Experience the best of Tawang, Arunachal Pradesh with our carefully curated 3 days itinerary full of scenic views and local culture.',
        price: 13000,
        duration: '3 Days',
        availableSeats: 6,
        startDate: new Date('2026-07-24'),
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Incredible Tarkarli Journey',
        destination: 'Tarkarli, Maharashtra',
        description: 'Experience the best of Tarkarli, Maharashtra with our carefully curated 5 days itinerary full of scenic views and local culture.',
        price: 22000,
        duration: '5 Days',
        availableSeats: 22,
        startDate: new Date('2026-08-05'),
        image: 'https://images.unsplash.com/photo-1570168007204-dfb528c68ddf?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Breathtaking Ooty Experience',
        destination: 'Ooty, Tamil Nadu',
        description: 'Experience the best of Ooty, Tamil Nadu with our carefully curated 3 days itinerary full of scenic views and local culture.',
        price: 25000,
        duration: '3 Days',
        availableSeats: 19,
        startDate: new Date('2026-09-04'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Alleppey Explorer',
        destination: 'Alleppey, Kerala',
        description: 'Experience the best of Alleppey, Kerala with our carefully curated 5 days itinerary full of scenic views and local culture.',
        price: 15000,
        duration: '5 Days',
        availableSeats: 10,
        startDate: new Date('2026-07-16'),
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Vibrant Pondicherry Explorer',
        destination: 'Pondicherry',
        description: 'Experience the best of Pondicherry with our carefully curated 8 days itinerary full of scenic views and local culture.',
        price: 20000,
        duration: '8 Days',
        availableSeats: 5,
        startDate: new Date('2026-07-09'),
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Vibrant Kaziranga Escape',
        destination: 'Kaziranga, Assam',
        description: 'Experience the best of Kaziranga, Assam with our carefully curated 4 days itinerary full of scenic views and local culture.',
        price: 41000,
        duration: '4 Days',
        availableSeats: 11,
        startDate: new Date('2026-05-07'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Peaceful Tirupati Escape',
        destination: 'Tirupati, Andhra Pradesh',
        description: 'Experience the best of Tirupati, Andhra Pradesh with our carefully curated 7 days itinerary full of scenic views and local culture.',
        price: 13000,
        duration: '7 Days',
        availableSeats: 6,
        startDate: new Date('2026-01-19'),
        image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Majestic Mount Abu Retreat',
        destination: 'Mount Abu, Rajasthan',
        description: 'Experience the best of Mount Abu, Rajasthan with our carefully curated 10 days itinerary full of scenic views and local culture.',
        price: 13000,
        duration: '10 Days',
        availableSeats: 7,
        startDate: new Date('2026-03-03'),
        image: 'https://images.unsplash.com/photo-1587474260580-5883ea07fe30?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Enchanting Kochi Adventure',
        destination: 'Kochi, Kerala',
        description: 'Experience the best of Kochi, Kerala with our carefully curated 5 days itinerary full of scenic views and local culture.',
        price: 17000,
        duration: '5 Days',
        availableSeats: 23,
        startDate: new Date('2026-10-02'),
        image: 'https://images.unsplash.com/photo-1587474260580-5883ea07fe30?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Cherrapunji Sojourn',
        destination: 'Cherrapunji, Meghalaya',
        description: 'Experience the best of Cherrapunji, Meghalaya with our carefully curated 10 days itinerary full of scenic views and local culture.',
        price: 46000,
        duration: '10 Days',
        availableSeats: 15,
        startDate: new Date('2026-05-07'),
        image: 'https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Breathtaking Kodaikanal Adventure',
        destination: 'Kodaikanal, Tamil Nadu',
        description: 'Experience the best of Kodaikanal, Tamil Nadu with our carefully curated 6 days itinerary full of scenic views and local culture.',
        price: 18000,
        duration: '6 Days',
        availableSeats: 19,
        startDate: new Date('2026-06-25'),
        image: 'https://images.unsplash.com/photo-1587474260580-5883ea07fe30?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Historic Varanasi Sojourn',
        destination: 'Varanasi, Uttar Pradesh',
        description: 'Experience the best of Varanasi, Uttar Pradesh with our carefully curated 3 days itinerary full of scenic views and local culture.',
        price: 46000,
        duration: '3 Days',
        availableSeats: 7,
        startDate: new Date('2026-09-07'),
        image: 'https://images.unsplash.com/photo-1623126040845-cb005e80db80?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Serene Andaman Islands Getaway',
        destination: 'Andaman Islands',
        description: 'Experience the best of Andaman Islands with our carefully curated 7 days itinerary full of scenic views and local culture.',
        price: 25000,
        duration: '7 Days',
        availableSeats: 14,
        startDate: new Date('2026-03-15'),
        image: 'https://images.unsplash.com/photo-1623126040845-cb005e80db80?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Rameshwaram Escape',
        destination: 'Rameshwaram, Tamil Nadu',
        description: 'Experience the best of Rameshwaram, Tamil Nadu with our carefully curated 10 days itinerary full of scenic views and local culture.',
        price: 10000,
        duration: '10 Days',
        availableSeats: 14,
        startDate: new Date('2026-11-04'),
        image: 'https://images.unsplash.com/photo-1514222026857-79758525baf3?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Incredible Nainital Getaway',
        destination: 'Nainital, Uttarakhand',
        description: 'Experience the best of Nainital, Uttarakhand with our carefully curated 4 days itinerary full of scenic views and local culture.',
        price: 45000,
        duration: '4 Days',
        availableSeats: 13,
        startDate: new Date('2026-05-20'),
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Serene Bandhavgarh Journey',
        destination: 'Bandhavgarh, Madhya Pradesh',
        description: 'Experience the best of Bandhavgarh, Madhya Pradesh with our carefully curated 6 days itinerary full of scenic views and local culture.',
        price: 50000,
        duration: '6 Days',
        availableSeats: 21,
        startDate: new Date('2026-08-09'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Adventurous Shimla Adventure',
        destination: 'Shimla, Himachal Pradesh',
        description: 'Experience the best of Shimla, Himachal Pradesh with our carefully curated 2 days itinerary full of scenic views and local culture.',
        price: 27000,
        duration: '2 Days',
        availableSeats: 5,
        startDate: new Date('2026-06-25'),
        image: 'https://images.unsplash.com/photo-1514222026857-79758525baf3?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Breathtaking Kanyakumari Retreat',
        destination: 'Kanyakumari, Tamil Nadu',
        description: 'Experience the best of Kanyakumari, Tamil Nadu with our carefully curated 10 days itinerary full of scenic views and local culture.',
        price: 38000,
        duration: '10 Days',
        availableSeats: 27,
        startDate: new Date('2026-07-18'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Incredible Jaisalmer Retreat',
        destination: 'Jaisalmer, Rajasthan',
        description: 'Experience the best of Jaisalmer, Rajasthan with our carefully curated 2 days itinerary full of scenic views and local culture.',
        price: 44000,
        duration: '2 Days',
        availableSeats: 16,
        startDate: new Date('2026-10-18'),
        image: 'https://images.unsplash.com/photo-1514222026857-79758525baf3?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Mystical Tawang Explorer',
        destination: 'Tawang, Arunachal Pradesh',
        description: 'Experience the best of Tawang, Arunachal Pradesh with our carefully curated 7 days itinerary full of scenic views and local culture.',
        price: 29000,
        duration: '7 Days',
        availableSeats: 30,
        startDate: new Date('2026-01-12'),
        image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Enchanting Kochi Holiday',
        destination: 'Kochi, Kerala',
        description: 'Experience the best of Kochi, Kerala with our carefully curated 7 days itinerary full of scenic views and local culture.',
        price: 16000,
        duration: '7 Days',
        availableSeats: 29,
        startDate: new Date('2026-09-28'),
        image: 'https://images.unsplash.com/photo-1570168007204-dfb528c68ddf?auto=format&fit=crop&w=800&q=80',
      },
      {
        title: 'Peaceful Rameshwaram Retreat',
        destination: 'Rameshwaram, Tamil Nadu',
        description: 'Experience the best of Rameshwaram, Tamil Nadu with our carefully curated 4 days itinerary full of scenic views and local culture.',
        price: 25000,
        duration: '4 Days',
        availableSeats: 30,
        startDate: new Date('2026-03-14'),
        image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?auto=format&fit=crop&w=800&q=80',
      }
    ]);

    await Booking.create([
      {
        customerName: regularUser.name,
        email: regularUser.email,
        seats: 2,
        packageId: packages[0]._id,
        totalPrice: packages[0].price * 2,
        status: 'confirmed'
      },
      {
        customerName: regularUser.name,
        email: regularUser.email,
        seats: 1,
        packageId: packages[1]._id,
        totalPrice: packages[1].price * 1,
        status: 'pending'
      }
    ]);

    console.log('Dummy data for Users, Packages, and Bookings successfully seeded!');
  } catch (err) {
    console.log('Error seeding data:', err);
  } finally {
    mongoose.connection.close();
  }
};

seedDB();
